name: 'Tests'
run-name: 'Run Testcase for Dailymotion API by @${{ github.actor }}'
on: [push, pull_request]

jobs:
  py_test:
    name: 'run unit test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Testing
        env:
          DM_BASE_URL: ${{ vars.ENDPOINT }}
          DM_CLIENT_API: ${{ secrets.CLIENT_API }}
          DM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python -m unittest discover -s tests -p "*.py"